### ISSUE TITLE
vgg9_direct_cifar10_t5_epoch100.pth.tar----Is this a well quantified model?

### ISSUE THREAD

**Issue by liyanjie001** [Intelligent-Computing-Lab-Yale/SpikeSim#2]
What is the model of this file(vgg9_direct_cifar10_t5_epoch100.pth.tar) inside the code and what is it used for? Is this a well quantified model?

**Comment by MoitraAbhi** [comment]
Hi sorry for the delayed response. The model used in the train.py is VGG9_Direct() model. Also, VGG9 has been used in prior works and is shown to achieve good performance across CIFAR10, CIFAR100 datasets. Please refer to the paper. https://arxiv.org/pdf/2010.01729.pdf. Note, in SpikeSim we use VGG9 model with direct input encoding.
