### ISSUE TITLE
Matrix size mismatch between coefficient matrix A and matrix B in the linear equation system.

### ISSUE THREAD

**Issue by Ikarosy** [Intelligent-Computing-Lab-Yale/SpikeSim#3]
Hi, I crush into an issue when reproducing your codes. Do you have any idea? or maybe the code itself is out-dated?
When I run the `Hardware-realistic Inference using the NICE` with exactly python commands as in readme, it appears to be an error report:
"
File "/home/codes/SpikeSim/NICE_Evaluation/hw_models_new.py", line 166, in signed_hw_conv_mod
sol = torch.linalg.solve(A, B)
RuntimeError: The size of tensor a (2304) must match the size of tensor b (288) at non-singleton dimension 0
"
I changed the original code in line 166, in signed_hw_conv_mod from `sol = torch.solve(B, A)` to `sol = torch.linalg.solve(A, B)` as pytorch recommends. But, this is the only change and it should make no differences. I also use your vgg9 checkpoint.

Then, I print the sizes of A and B with `print(B.size(), A.size())` in line 165, which turns out to be:
“
torch.Size([2304, 64, 1024]) torch.Size([288, 64, 64])
torch.Size([2304, 64, 1024]) torch.Size([288, 64, 64])
torch.Size([2304, 64, 1024]) torch.Size([288, 64, 64])
torch.Size([2304, 64, 1024]) torch.Size([288, 64, 64])
torch.Size([2304, 64, 1024]) torch.Size([288, 64, 64])
torch.Size([2304, 64, 1024]) torch.Size([288, 64, 64])
torch.Size([2304, 64, 1024]) torch.Size([288, 64, 64])
torch.Size([2304, 64, 1024]) torch.Size([288, 64, 64])

”
Clearly, the sizes of A and B are mismatched for a linear equation system. Do you have any idea about this issue? I would greatly appreciate it if you could solve it.

Thanks for you time.

**Comment by MoitraAbhi** [comment]
Hello, thank you for trying out our SpikeSim tool. Can you let us know the GPU and pytorch version you are currently using?
FYI, we have uploaded the requirements.txt file for code reproducibility. Please let us know if you have any questions.

**Comment by Ikarosy** [comment]
I am not sure if it is due to the torch version.  But, it reports a matrix size mismatch. I currently won't pay much attention to this issue because another more important issue is found and requires to be solved with the help of the authors, I may try to solve this issue in the future. For now, I close this issue and dedicate myself to solving the other issue, making sure SpikeSim can be correctly used to benchmark SNNs on IMC devices.
