### ISSUE TITLE
Latency evaluation funtion seems to be wrongly coded

### ISSUE THREAD

**Issue by Ikarosy** [Intelligent-Computing-Lab-Yale/SpikeSim#4]
Hi, thanks for your SpikeSim work at TCAD2023.  I checked your simulator script which is `ela_spikesim.py` along with the published paper.  And, the function `latency_gen` seems to be wrongly coded to me.  

Here is the confusing part: 

`checkpoints_1.append(int(cp[i]*out_dim_list[i]*out_dim_list[i]*out_ch_list[i])*time_steps)` in Line 162 seems to aim at calculating the overlapped Time-Stamp as illustrated in Fig. 11 of the paper, where `time_steps` is considered. So does Line 177: `checkpoints_2.append(int(out_dim_list[i]*out_dim_list[i]*out_ch_list[i])*time_steps)`.

But, at the end of the latency calculation: 
`print(f' layerwise_latency {(np.array(halts)-np.array(starts))*PE_cycle*time_steps} ns')` in Line 193, `time_steps` is re-considered again.

Is it correctly written? The  `time_steps` 's in both Line 163 and 177 should be eliminated or just deleting the `time_steps` in  Line 193 if I read the codes and the paper correctly. The codes are simple. I think I did not mistake the coding logic.  I did not 
fully check if the paper statistics were calculated correctly, e.g., Table V.  But the vgg9 example as used in this code seems to mismatch the results reported in the paper.

I would greatly appreciate it if you could solve this issue. Maybe I missed something or got some parts of the algorithm mistaken. I need to make sure of the correct usage of the SpikeSim platform. Thanks in advance.

**Comment by Ikarosy** [comment]
Here is the result that I directly run `python ela_spikesim.py ` without changing a thing:
```
Layers in order
No. of PEs 48.0
No. of Tiles 6.0
total_compute_area 8425528.755833998 µm^2
total_energy 15906934.026240002 pJ
Layers in order
 layerwise_latency [1.7039308e+08 4.2597880e+07 8.5196280e+07 2.1298680e+07 4.2597880e+07
 4.2597880e+07 1.0649080e+07] ns
 total_latency 314.16319999999996 ms
```
except for `total_latency 314.16319999999996 ms` is calculated by adding ` print(f' total_latency {np.array(halts)[-1]*PE_cycle*time_steps * 10 ** -6} ms')` in the end of `latency_gen`. The results are quite different from what is reported in the paper. I wonder which part did I miss or incorrectly use.

**Comment by MoitraAbhi** [comment]
We highly appreciate your interest in making SpikeSim better. We have addressed the comments.
